import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as XLSX from 'xlsx';
import { actionDiagnosis, classify, compareMetrics, cpcDiagnosis, DEFAULT_SETTINGS, funnelDiagnosis, groupRows, leakStage, metrics, normalizeRow, placementType, productContributionMargin, productMarginResolution, updateProductContributionMargin, weeklyGroups } from './analysis';
import { sampleRows } from './sample';
import './styles.css';

const nav = [
  ['dashboard','▦','대시보드'], ['leak','⌁','누수 키워드'], ['hero','✦','효자 키워드'], ['product','◇','상품 진단'],
  ['weekly','◫','주간 비교'], ['placement','▤','지면 분석'], ['rows','☷','행별 진단'], ['master','□','상품 마스터'], ['settings','⚙','설정']
];
const won = n => `₩${Math.round(n || 0).toLocaleString('ko-KR')}`;
const pct = n => `${(n || 0).toFixed(1)}%`;
const number = n => Math.round(n || 0).toLocaleString('ko-KR');

function Metric({label,value,sub,tone,icon}) { return <article className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div><p>{label}</p><strong>{value}</strong><small>{sub}</small></div></article> }
function Empty({children}) { return <div className="empty"><span>⌁</span><h3>표시할 데이터가 없습니다</h3><p>{children}</p></div> }
function Table({groups, first='키워드'}) { return <div className="table-wrap"><table><thead><tr><th>{first}</th><th>클릭</th><th>실제 광고비(VAT 포함)</th><th>주문</th><th>매출</th><th>실제 ROAS</th><th>실제 CPA</th></tr></thead><tbody>{groups.map(g=><tr key={g.name}><td><b>{g.name}</b></td><td>{number(g.clicks)}</td><td>{won(g.actualCost)}</td><td>{number(g.orders)}</td><td>{won(g.sales)}</td><td><span className={g.actualRoa>=g.requiredRoa?'positive':''}>{pct(g.actualRoa)}</span></td><td>{won(g.actualCpa)}</td></tr>)}</tbody></table></div> }

function App() {
  const [page,setPage] = useState('dashboard');
  const [rows,setRows] = useState(()=>JSON.parse(localStorage.getItem('coupang-rows')||'null') || sampleRows);
  const [settings,setSettings] = useState(()=>JSON.parse(localStorage.getItem('coupang-settings')||'null') || DEFAULT_SETTINGS);
  const [notes,setNotes] = useState(()=>JSON.parse(localStorage.getItem('coupang-weekly-notes')||'{}'));
  const [productMaster,setProductMaster] = useState(()=>JSON.parse(localStorage.getItem('coupang-product-master-v2')||'[]'));
  const [uploadOpen,setUploadOpen] = useState(false), [raw,setRaw] = useState(''), [query,setQuery] = useState(''), [notice,setNotice] = useState('');
  const fileRef=useRef();
  useEffect(()=>localStorage.setItem('coupang-rows',JSON.stringify(rows)),[rows]);
  useEffect(()=>localStorage.setItem('coupang-settings',JSON.stringify(settings)),[settings]);
  useEffect(()=>localStorage.setItem('coupang-weekly-notes',JSON.stringify(notes)),[notes]);
  useEffect(()=>localStorage.setItem('coupang-product-master-v2',JSON.stringify(productMaster)),[productMaster]);
  const m=useMemo(()=>metrics(rows,settings),[rows,settings]);
  const keywords=useMemo(()=>groupRows(rows,'keyword',settings),[rows,settings]);
  const products=useMemo(()=>groupRows(rows,'product',settings),[rows,settings]);
  const placements=useMemo(()=>groupRows(rows,'placement',settings),[rows,settings]);
  const weeks=useMemo(()=>weeklyGroups(rows,settings),[rows,settings]);
  const filtered=rows.filter(r=>[r.keyword,r.product,r.placement].some(v=>v.toLowerCase().includes(query.toLowerCase())));
  const saveRows = parsed => { setRows(old => { const byId=new Map(old.map(r=>[`${r.date}|${r.productId||r.product}|${r.keyword}|${r.placement}`,r])); parsed.forEach(r=>byId.set(`${r.date}|${r.productId||r.product}|${r.keyword}|${r.placement}`,r)); return [...byId.values()].map((r,i)=>({...r,id:i+1})); }); };
  const importWorkbook = async file => { try { const data=await file.arrayBuffer(); const wb=XLSX.read(data); const sheet=wb.Sheets[wb.SheetNames[0]]; const parsed=XLSX.utils.sheet_to_json(sheet).map(normalizeRow); if(!parsed.length) throw Error('데이터가 없습니다.'); saveRows(parsed); setUploadOpen(false); flash(`${parsed.length}개 행을 주간 데이터에 저장했습니다.`); } catch(e){flash(`업로드 실패: ${e.message}`)} };
  const parseRaw=()=>{ try { const text=raw.trim(); if(!text) return; const delim=text.includes('\t')?'\t':','; const lines=text.split(/\r?\n/).map(l=>l.split(delim)); const headers=lines.shift(); saveRows(lines.filter(x=>x.some(Boolean)).map((line,i)=>normalizeRow(Object.fromEntries(headers.map((h,j)=>[h.trim(),line[j]?.trim()])),i))); setUploadOpen(false); flash('RAW 데이터를 주간 데이터에 저장했습니다.'); }catch(e){flash('RAW 데이터 형식을 확인해주세요.')} };
  const flash=t=>{setNotice(t);setTimeout(()=>setNotice(''),3000)};
  const title=nav.find(n=>n[0]===page)?.[2];
  return <div className="app">
    <aside><div className="brand"><div className="logo">C</div><div><b>쿠팡 광고 분석기</b><small>AD INTELLIGENCE</small></div></div><nav>{nav.map(([id,icon,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><span>{icon}</span>{label}{id==='leak'&&<em>{keywords.filter(k=>leakStage(k)>0).length}</em>}</button>)}</nav><div className="side-help"><b>분석이 처음이신가요?</b><p>쿠팡 광고 보고서를 올리면 자동으로 진단해 드려요.</p><button onClick={()=>setUploadOpen(true)}>데이터 업로드</button></div><div className="version">v2.0.0 · 기존 데이터와 주간 기록 자동 보존</div></aside>
    <main><header><div><h1>{title}</h1><p>광고 성과를 한눈에 확인하고, 개선 포인트를 발견하세요.</p></div><div className="head-actions"><button className="icon-btn" aria-label="알림">♢</button><button className="upload" onClick={()=>setUploadOpen(true)}>↑ &nbsp;데이터 업로드</button></div></header>
      {page==='dashboard'&&<Dashboard m={m} keywords={keywords} placements={placements} />}
      {page==='leak'&&<LeakPage groups={keywords.filter(k=>leakStage(k)>0)} />}
      {page==='hero'&&<ListPage title="효자 키워드" hint={`목표 ROAS ${settings.targetRoa}% 이상인 키워드입니다.`} groups={keywords.filter(k=>k.orders>0&&k.roa>=settings.targetRoa)} first="효자 키워드" empty="목표를 달성한 키워드가 아직 없습니다." />}
      {page==='product'&&<ProductDiagnosis groups={products} productMaster={productMaster} />}
      {page==='weekly'&&<Weekly weeks={weeks} settings={settings} notes={notes} setNotes={setNotes}/>}
      {page==='placement'&&<Placement groups={placements}/>}
      {page==='rows'&&<Rows rows={filtered} query={query} setQuery={setQuery} settings={settings}/>}
      {page==='master'&&<Master groups={products} productMaster={productMaster} setProductMaster={setProductMaster} />}
      {page==='settings'&&<Settings value={settings} setValue={setSettings} reset={()=>{setSettings(DEFAULT_SETTINGS);flash('기본 설정으로 복원했습니다.')}}/>}
    </main>{notice&&<div className="toast">✓ {notice}</div>}
    {uploadOpen&&<div className="modal-back" onMouseDown={e=>e.target===e.currentTarget&&setUploadOpen(false)}><section className="modal"><button className="close" onClick={()=>setUploadOpen(false)}>×</button><div className="modal-icon">↑</div><h2>광고 데이터 불러오기</h2><p>XLSX, XLS, CSV 파일을 올리거나 원본 데이터를 붙여넣으세요.</p><div className="drop" onClick={()=>fileRef.current.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();importWorkbook(e.dataTransfer.files[0])}}><b>파일을 끌어다 놓거나 클릭하세요</b><small>.xlsx · .xls · .csv (최대 20MB)</small><input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>importWorkbook(e.target.files[0])}/></div><div className="or"><span/>또는 RAW 붙여넣기<span/></div><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'날짜\t상품명\t키워드\t노출수\t클릭수\t광고비\t주문수\t매출액\n2026-08-01\t상품 A\t검색어 A\t1000\t30\t12000\t2\t90000'}/><button className="primary full" disabled={!raw.trim()} onClick={parseRaw}>붙여넣은 데이터 분석</button><button className="sample" onClick={()=>{setRows(sampleRows);setUploadOpen(false);flash('샘플 데이터를 불러왔습니다.')}}>샘플 데이터로 둘러보기 →</button></section></div>}
  </div>
}

function Dashboard({m,keywords,placements}) { const max=Math.max(...placements.map(p=>p.sales),1); return <><div className="period"><button>최근 전체 기간⌄</button><span>VAT 포함 실광고비 기준</span></div><section className="metric-grid"><Metric label="실제 광고비" value={won(m.actualCost)} sub={`VAT 포함 · CPC ${won(m.cpc)}`} icon="₩" tone="blue"/><Metric label="광고 매출" value={won(m.sales)} sub={`실제 ROAS ${pct(m.actualRoa)}`} icon="↗" tone="green"/><Metric label="주문수" value={number(m.orders)} sub={`실제 CPA ${won(m.actualCpa)}`} icon="▢" tone="purple"/><Metric label="예상 순이익" value={won(m.expectedProfit)} sub={`전환율 ${pct(m.cvr)}`} icon="✦" tone="orange"/></section><div className="info-strip"><span>◎</span><div><b>유입 추정 {number(m.estimatedVisits)}명</b><p>광고 클릭과 일반적인 중복 유입률을 반영한 참고 지표입니다.</p></div><strong>CTR {pct(m.ctr)}</strong></div><div className="two-col"><section className="panel"><div className="panel-title"><div><h2>지면별 광고 매출</h2><p>노출 지면에 따른 매출 기여도</p></div></div><div className="bars">{placements.map((p,i)=><div className="bar-row" key={p.name}><span>{p.name}</span><div><i style={{width:`${p.sales/max*100}%`}} className={`bar c${i}`}/></div><b>{won(p.sales)}</b></div>)}</div></section><section className="panel"><div className="panel-title"><div><h2>키워드 성과 TOP 5</h2><p>광고 매출 기준 상위 키워드</p></div></div><div className="ranking">{[...keywords].sort((a,b)=>b.sales-a.sales).slice(0,5).map((k,i)=><div key={k.name}><em>{i+1}</em><span><b>{k.name}</b><small>{number(k.clicks)} 클릭 · {number(k.orders)} 주문</small></span><strong>{won(k.sales)}<small>실제 ROAS {pct(k.actualRoa)}</small></strong></div>)}</div></section></div><section className="panel health"><div className="panel-title"><div><h2>오늘의 광고 진단</h2><p>VAT와 손익 기준으로 지금 확인할 항목입니다.</p></div></div><div className="health-grid"><div className="danger-card"><span>!</span><div><b>누수 키워드</b><strong>{keywords.filter(k=>leakStage(k)>0).length}개</strong><small>3단계로 위험도를 구분했어요</small></div></div><div className="good-card"><span>✦</span><div><b>확대 검토</b><strong>{keywords.filter(k=>actionDiagnosis(k).label==='확대 검토').length}개</strong><small>필요 ROAS를 여유 있게 넘었어요</small></div></div><div className="neutral-card"><span>◉</span><div><b>분석 데이터</b><strong>{number(m.clicks)} 클릭</strong><small>충분한 데이터가 쌓이고 있어요</small></div></div></div></section></> }
function ListPage({title,hint,groups,first,empty}) { return <section className="panel page-panel"><div className="panel-title"><div><h2>{title}</h2><p>{hint}</p></div><span className="count">총 {groups.length}개</span></div>{groups.length?<Table groups={groups} first={first}/>:<Empty>{empty}</Empty>}</section> }
function LeakPage({groups}) { return <section className="panel page-panel"><div className="panel-title"><div><h2>누수 키워드 3단계</h2><p>1단계(초기) · 2단계(주의) · 3단계(심각)로 광고비 누수를 구분합니다.</p></div><span className="count">총 {groups.length}개</span></div><div className="table-wrap"><table><thead><tr><th>키워드</th><th>단계</th><th>클릭</th><th>실제 광고비</th><th>권장 조치</th></tr></thead><tbody>{groups.sort((a,b)=>leakStage(b)-leakStage(a)).map(g=><tr key={g.name}><td><b>{g.name}</b></td><td><span className={`badge ${leakStage(g)===3?'danger':'warn'}`}>{leakStage(g)}단계</span></td><td>{number(g.clicks)}</td><td>{won(g.actualCost)}</td><td>{['','데이터 수집','검색어·입찰 점검','중단 또는 제외 검토'][leakStage(g)]}</td></tr>)}</tbody></table></div></section> }
function ProductDiagnosis({groups,productMaster}) { const [tab,setTab]=useState('cpc'); return <><div className="analysis-tabs" role="tablist"><button className={tab==='diagnosis'?'active':''} onClick={()=>setTab('diagnosis')}>광고 진단</button><button className={tab==='cpc'?'active':''} onClick={()=>setTab('cpc')}>누수 · CPC 분석</button></div>{tab==='diagnosis'?<section className="panel page-panel"><div className="panel-title"><div><h2>상품별 액션 · 퍼널 진단</h2><p>실제 ROAS와 상품별 필요 ROAS를 비교해 다음 액션을 제안합니다.</p></div></div><div className="table-wrap"><table><thead><tr><th>상품 / 상품ID</th><th>실제 ROAS</th><th>필요 ROAS</th><th>퍼널</th><th>액션 진단</th></tr></thead><tbody>{groups.map(g=>{const d=actionDiagnosis(g);return <tr key={g.name}><td><b>{g.name}</b><small className="block">{g.rows[0]?.productId||g.name}</small></td><td>{pct(g.actualRoa)}</td><td>{Number.isFinite(g.requiredRoa)?pct(g.requiredRoa):'-'}</td><td>{funnelDiagnosis(g)}</td><td><span className={`badge ${d.level}`} title={d.message}>{d.label}</span></td></tr>})}</tbody></table></div></section>:<CpcAnalysis groups={groups} productMaster={productMaster}/>}</> }
function CpcAnalysis({groups,productMaster}) { const [filter,setFilter]=useState('all'); const analyzed=groups.map(group=>{const key=group.rows[0]?.productId||group.name;const margin=productMarginResolution(productMaster,key,group.name);return {group,diagnosis:cpcDiagnosis(group,productContributionMargin(productMaster,key,group.name),margin.status)}}).sort((a,b)=>a.diagnosis.priority-b.diagnosis.priority||b.group.actualCost-a.group.actualCost); const visible=filter==='all'?analyzed:analyzed.filter(x=>x.diagnosis.group===filter); const count=group=>analyzed.filter(x=>x.diagnosis.group===group).length; return <section className="cpc-page"><div className="cpc-heading"><div><h2>누수 · CPC 분석</h2><p>실제 광고비(VAT 포함)와 손익 기준으로 우선 점검할 상품을 보여드립니다.</p></div><div className="summary-chips"><span><small>전체</small><b>{analyzed.length}</b></span><span className="check"><small>우선 점검</small><b>{count('check')}</b></span><span className="scale"><small>확대 후보</small><b>{count('scale')}</b></span><span className="info"><small>판단 보류</small><b>{count('insufficient')}</b></span></div></div><div className="margin-guide"><span>ⓘ</span><p><b>손익분기 CPC 안내</b> 상품 마스터의 광고 전 개당 마진 × CVR로 계산하며, 마진이 없으면 판단을 보류합니다.</p></div><div className="cpc-filters" aria-label="분석 결과 필터">{[['all','전체'],['check','점검 필요'],['scale','확대 후보'],['insufficient','판단 보류']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}<em>{id==='all'?analyzed.length:count(id)}</em></button>)}</div>{visible.length?<div className="cpc-grid">{visible.map(({group,diagnosis})=><CpcCard key={group.name} group={group} diagnosis={diagnosis}/>)}</div>:<Empty>선택한 조건에 해당하는 상품이 없습니다.</Empty>}</section> }
function CpcCard({group:g,diagnosis:d}) { const ctrText=g.ctr<.5?'낮음':g.ctr<1?'보통':'양호'; const cvrText=!g.orders?'전환 없음':g.cvr<2?'낮음':'양호'; const cpcText=d.badges.includes('마진 연결 필요')?'마진 연결 필요':d.breakEvenCpc===null?'마진 입력 필요':g.cpc>d.breakEvenCpc?'손익 기준 초과':'허용 범위'; const roaText=g.actualRoa<g.requiredRoa?'최소 미달':'기준 충족'; return <article className={`cpc-card ${d.kind}`}><div className="cpc-card-head"><div><small>{g.rows[0]?.productId||'상품ID 미등록'}</small><h3>{g.name}</h3></div><div className="status-badges">{d.badges.slice(0,2).map(x=><span key={x}>{x}</span>)}</div></div><div className="core-metrics"><div><small>CTR</small><strong>{pct(g.ctr)}</strong><em>{ctrText}</em></div><div><small>CVR</small><strong>{pct(g.cvr)}</strong><em>{cvrText}</em></div><div><small>실제 CPC</small><strong>{won(g.cpc)}</strong><em>{cpcText}</em></div><div><small>실제 ROAS</small><strong>{pct(g.actualRoa)}</strong><em>{roaText}</em></div></div><div className="compact-totals"><span>노출 <b>{number(g.impressions)}</b></span><span>클릭 <b>{number(g.clicks)}</b></span><span>주문 <b>{number(g.orders)}</b></span><span>실제 광고비 <b>{won(g.actualCost)}</b></span></div><p className="one-diagnosis">{d.diagnosis}</p><div className="next-actions"><small>다음 액션</small>{d.actions.slice(0,3).map(x=><span key={x}>{x}</span>)}</div></article> }
function Delta({value,money=false}) { return <span className={value>=0?'delta-up':'delta-down'}>{value>=0?'▲':'▼'} {Math.abs(value).toFixed(1)}%</span> }
function Weekly({weeks,settings,notes,setNotes}) { const current=weeks[0], previous=weeks[1], delta=current&&compareMetrics(current,previous); const withProductId=list=>list.map(r=>({...r,productKey:r.productId||r.product})); const productWeeks=current?groupRows(withProductId(current.rows),'productKey',settings):[]; const previousProducts=previous?Object.fromEntries(groupRows(withProductId(previous.rows),'productKey',settings).map(x=>[x.name,x])):{}; if(!current)return <Empty>날짜가 포함된 광고 데이터를 업로드하세요.</Empty>; return <><section className="weekly-summary"><div><small>이번 주</small><h2>{current.name}</h2><p>{previous?`${previous.name} 대비 성과`:'지난주 데이터가 없습니다.'}</p></div>{[['실제 광고비','actualCost',won],['매출','sales',won],['주문','orders',number],['실제 ROAS','actualRoa',pct]].map(([label,key,format])=><article key={key}><small>{label}</small><strong>{format(current[key])}</strong>{previous&&<Delta value={delta[key]}/>}</article>)}</section><section className="panel"><div className="panel-title"><div><h2>상품ID별 주간 비교</h2><p>상품별 이번 주 성과와 지난주 증감을 확인하고 메모를 남기세요.</p></div></div><div className="table-wrap"><table><thead><tr><th>상품ID / 상품명</th><th>실제 광고비</th><th>실제 ROAS</th><th>지난주 대비 매출</th><th>액션</th><th>주간 메모</th></tr></thead><tbody>{productWeeks.map(g=>{const prev=previousProducts[g.name], d=actionDiagnosis(g), noteKey=`${current.name}|${g.name}`;return <tr key={g.name}><td><b>{g.name}</b><small className="block">{g.rows[0]?.product}</small></td><td>{won(g.actualCost)}</td><td>{pct(g.actualRoa)}</td><td>{prev?<Delta value={compareMetrics(g,prev).sales}/>:<span className="muted">신규</span>}</td><td><span className={`badge ${d.level}`}>{d.label}</span></td><td><input className="memo" value={notes[noteKey]||''} onChange={e=>setNotes({...notes,[noteKey]:e.target.value})} placeholder="이번 주 메모"/></td></tr>})}</tbody></table></div></section><section className="panel summary-box"><h2>주간 요약</h2><p>이번 주 실제 광고비는 <b>{won(current.actualCost)}</b>, 매출은 <b>{won(current.sales)}</b>, 실제 ROAS는 <b>{pct(current.actualRoa)}</b>입니다. {previous&&`지난주 대비 매출은 ${delta.sales>=0?'증가':'감소'}했습니다.`}</p></section></> }
function Placement({groups}) { const typed=groupRows(groups.flatMap(g=>g.rows).map(r=>({...r,placementType:placementType(r.placement)})),'placementType'); const non=typed.find(g=>g.name==='비검색'); const total=typed.reduce((a,g)=>a+g.actualCost,0); return <>{non&&total&&non.actualCost/total>.35&&<div className="warning">⚠ 비검색 광고비가 전체의 {pct(non.actualCost/total*100)}입니다. 효율이 낮은 지면의 예산을 점검하세요.</div>}<div className="metric-grid compact">{typed.map((g,i)=><Metric key={g.name} label={g.name} value={won(g.sales)} sub={`실제 ROAS ${pct(g.actualRoa)} · 비용 ${won(g.actualCost)}`} icon={['⌕','▦','◎'][i]||'◇'} tone={['blue','green','purple'][i%3]}/>)}</div><ListPage title="지면별 상세 성과" hint="검색 / 비검색 / 오디언스 플러스 지면의 투자 효율입니다." groups={groups} first="광고 지면"/></>}
function Rows({rows,query,setQuery,settings}) {return <section className="panel page-panel"><div className="panel-title"><div><h2>행별 진단</h2><p>원본 데이터 한 행씩 진단 결과와 개선 방향을 확인합니다.</p></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕ 상품, 키워드 검색"/></div><div className="table-wrap"><table><thead><tr><th>날짜 / 상품</th><th>키워드</th><th>실제 광고비</th><th>주문</th><th>실제 ROAS</th><th>진단</th></tr></thead><tbody>{rows.map(r=>{const d=classify(r,settings), mm=metrics([r],settings);return <tr key={r.id}><td><b>{r.product}</b><small className="block">{r.date}</small></td><td>{r.keyword}</td><td>{won(mm.actualCost)}</td><td>{r.orders}</td><td>{pct(mm.actualRoa)}</td><td><span className={`badge ${d.level}`} title={d.message}>{d.label}</span></td></tr>})}</tbody></table></div></section>}
function Master({groups,productMaster,setProductMaster}) {return <section className="panel page-panel"><div className="panel-title"><div><h2>상품 마스터</h2><p>광고 전 개당 마진을 입력하면 손익분기 CPC에 우선 적용됩니다.</p></div><button className="outline">+ 상품 추가</button></div><div className="product-grid">{groups.map((g,i)=>{const key=g.rows[0]?.productId||g.name;return <article className="product-card" key={g.name}><div className={`product-thumb t${i%3}`}>◇</div><div><small>{key}</small><h3>{g.name}</h3><p>{number(g.impressions)}회 노출 · {number(g.clicks)}회 클릭</p><div><span>누적 매출 <b>{won(g.sales)}</b></span><span>ROAS <b>{pct(g.roa)}</b></span></div><label className="margin-input"><span>광고 전 개당 마진</span><div><input type="number" min="0" value={productContributionMargin(productMaster,key,g.name)||''} onChange={e=>setProductMaster(updateProductContributionMargin(productMaster,key,g.name,e.target.value))} placeholder="마진 입력"/><em>원</em></div></label></div></article>})}</div></section>}
function Settings({value,setValue,reset}) { const fields=[['marginRate','평균 마진율','상품 매출에서 원가를 제외한 비율','%'],['feeRate','쿠팡 수수료율','카테고리 평균 판매 수수료','%'],['shippingCost','건당 배송비','주문 1건당 부담하는 평균 배송비','원'],['vatRate','광고비 VAT','실제 광고비에 더하는 부가세율','%'],['targetRoa','목표 ROAS','효자 키워드를 판단하는 기준','%']]; return <section className="panel settings"><div className="panel-title"><div><h2>분석 기준 설정</h2><p>실제 광고비, CPA, 필요 ROAS와 예상 순이익 계산에 적용됩니다.</p></div></div>{fields.map(([key,label,hint,unit])=><label key={key}><span><b>{label}</b><small>{hint}</small></span><div><input type="number" value={value[key]??DEFAULT_SETTINGS[key]} onChange={e=>setValue({...value,[key]:Number(e.target.value)})}/><em>{unit}</em></div></label>)}<div className="setting-actions"><button onClick={reset}>기본값 복원</button><span>변경사항은 자동으로 저장됩니다.</span></div></section>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
