import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import * as XLSX from 'xlsx';
import { actionStatus, classify, DEFAULT_SETTINGS, funnelDiagnosis, groupRows, leakLevel, metrics, normalizeRow, placementCategory, profitabilityStatus } from './analysis';
import { compareValue, productComparison, saveWeek, STORAGE, weekRange } from './weekly';
import { sampleRows } from './sample';
import SourcingCalculator from './SourcingCalculator';
import './styles.css';

const nav=[['dashboard','▦','주간 대시보드'],['weekly','⇄','상품 주간 비교'],['leak','⌁','누수 키워드'],['hero','✦','효자 키워드'],['product','◇','상품 진단'],['placement','▤','지면 분석'],['rows','☷','행별 진단'],['master','□','상품 마스터'],['sourcing','⌗','소싱 계산기'],['settings','⚙','설정']];
const won=n=>`${Math.round(n||0).toLocaleString('ko-KR')}원`, pct=n=>`${(n||0).toFixed(1)}%`, number=n=>Math.round(n||0).toLocaleString('ko-KR');
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
function Delta({now,before,inverse=false,format=pct}){const d=compareValue(now,before), good=d.direction==='same'?null:(d.direction==='down')===inverse;return <small className={`delta ${good===true?'good-text':good===false?'bad-text':''}`}>{d.direction==='up'?'▲':d.direction==='down'?'▼':'―'} {d.rate===null?'신규':pct(Math.abs(d.rate))} <span>({format(d.difference)})</span></small>}
function Kpi({label,value,now,before,format=won,inverse=false,help}){return <article className="week-kpi"><p>{label}{help&&<i title={help}>?</i>}</p><strong>{value}</strong>{before!==undefined&&<Delta now={now} before={before} inverse={inverse} format={format}/>}</article>}
function Badge({status}){return <span className={`badge ${status.level}`}>{status.icon} {status.label}</span>}
function Table({groups,first='키워드',actual=true}){return <div className="table-wrap"><table><thead><tr><th>{first}</th><th>클릭</th><th>광고비</th><th>실제 광고비</th><th>주문</th><th>{actual?'실제 ROAS':'ROAS'}</th><th>CPA</th></tr></thead><tbody>{groups.map(g=><tr key={g.name}><td><b>{g.name}</b></td><td>{number(g.clicks)}</td><td>{won(g.cost)}</td><td>{won(g.actualCost)}</td><td>{number(g.orders)}</td><td>{pct(actual?g.actualRoa:g.roa)}</td><td>{won(g.cpa)}</td></tr>)}</tbody></table></div>}
function Empty({children}){return <div className="empty"><span>⌁</span><h3>표시할 데이터가 없습니다</h3><p>{children}</p></div>}

function App(){
 const [page,setPage]=useState('dashboard'),[rows,setRows]=useState(()=>read('coupang-rows',sampleRows));
 const [settings,setSettings]=useState(()=>({...DEFAULT_SETTINGS,...read('coupang-settings',{})}));
 const [weeks,setWeeks]=useState(()=>read(STORAGE.weeks,[])),[master,setMaster]=useState(()=>read(STORAGE.master,{})),[notes,setNotes]=useState(()=>read(STORAGE.notes,{}));
 const [previousId,setPreviousId]=useState(''),[uploadOpen,setUploadOpen]=useState(false),[raw,setRaw]=useState(''),[query,setQuery]=useState(''),[notice,setNotice]=useState(''); const fileRef=useRef();
 useEffect(()=>localStorage.setItem('coupang-rows',JSON.stringify(rows)),[rows]); useEffect(()=>localStorage.setItem('coupang-settings',JSON.stringify(settings)),[settings]);
 useEffect(()=>localStorage.setItem(STORAGE.weeks,JSON.stringify(weeks)),[weeks]); useEffect(()=>localStorage.setItem(STORAGE.master,JSON.stringify(master)),[master]); useEffect(()=>localStorage.setItem(STORAGE.notes,JSON.stringify(notes)),[notes]);
 const previous=weeks.find(w=>w.id===previousId) || weeks.find(w=>w.label!==weekRange(rows)); const previousRows=previous?.rows||[];
 const m=useMemo(()=>metrics(rows,settings),[rows,settings]), pm=useMemo(()=>metrics(previousRows,settings),[previousRows,settings]);
 const keywords=useMemo(()=>groupRows(rows,'keyword',settings),[rows,settings]), products=useMemo(()=>groupRows(rows,'productId',settings),[rows,settings]), placements=useMemo(()=>groupRows(rows,'placement',settings),[rows,settings]);
 const comparisons=useMemo(()=>productComparison(rows,previousRows,settings),[rows,previousRows,settings]);
 const flash=t=>{setNotice(t);setTimeout(()=>setNotice(''),3000)};
 const importRows=parsed=>{if(!parsed.length)throw Error('데이터가 없습니다.');setRows(parsed);setUploadOpen(false);flash(`${parsed.length}개 행을 불러왔습니다.`)};
 const importWorkbook=async file=>{try{if(file.size>20*1024*1024)throw Error('20MB 이하 파일만 가능합니다.');const match=file.name.match(/_(\d{8})_(\d{8})(?:\.[^.]+)?$/);globalThis.__coupangReportContext=match?{start:`${match[1].slice(0,4)}-${match[1].slice(4,6)}-${match[1].slice(6,8)}`,end:`${match[2].slice(0,4)}-${match[2].slice(4,6)}-${match[2].slice(6,8)}`} : {};const wb=XLSX.read(await file.arrayBuffer());importRows(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]).map(normalizeRow))}catch(e){flash(`업로드 실패: ${e.message}`)}finally{delete globalThis.__coupangReportContext}};
 const parseRaw=()=>{try{const text=raw.trim();if(!text)return;const delim=text.includes('\t')?'\t':',';const lines=text.split(/\r?\n/).map(l=>l.split(delim)),headers=lines.shift();importRows(lines.filter(x=>x.some(Boolean)).map((line,i)=>normalizeRow(Object.fromEntries(headers.map((h,j)=>[h.trim(),line[j]?.trim()])),i)))}catch{flash('RAW 데이터 형식을 확인해주세요.')}};
 const saveCurrent=()=>{const next=saveWeek(weeks,rows);setWeeks(next);flash(`${next[0].label} 데이터를 저장했습니다.`)};
 const title=nav.find(n=>n[0]===page)?.[2];
 const headerText=page==='sourcing'?'원가를 넣고 목표 마진별 판매가와 최소 ROAS를 빠르게 계산하세요.':'이번 주 성과를 확인하고 다음 주 운영 액션을 결정하세요.';
 return <div className="app"><aside><div className="brand"><div className="logo">C</div><div><b>쿠팡 광고 분석기</b><small>WEEKLY AD OPS</small></div></div><nav>{nav.map(([id,icon,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><span>{icon}</span>{label}{id==='leak'&&<em>{keywords.filter(k=>leakLevel(k,settings).rank>=2).length}</em>}</button>)}</nav><div className="side-help"><b>매주 광고를 점검하세요</b><p>보고서를 올리고 지난주 대비 변화와 다음 액션을 확인하세요.</p><button onClick={()=>setUploadOpen(true)}>데이터 업로드</button></div><div className="version">v2.0 · 데이터는 브라우저에만 저장</div></aside>
 <main><header><div><h1>{title}</h1><p>{headerText}</p></div>{page!=='sourcing'&&<div className="head-actions"><button className="save-week" onClick={saveCurrent}>＋ 이번 주 데이터 저장</button><button className="upload" onClick={()=>setUploadOpen(true)}>↑ 데이터 업로드</button></div>}</header>
 {page==='dashboard'&&<Dashboard m={m} pm={pm} products={products} comparisons={comparisons} rows={rows} settings={settings} master={master} previous={previous} weeks={weeks} previousId={previousId} setPreviousId={setPreviousId} setPage={setPage}/>}
 {page==='weekly'&&<Weekly comparisons={comparisons} master={master} settings={settings} notes={notes} setNotes={setNotes} currentLabel={weekRange(rows)} previous={previous}/>}
 {page==='leak'&&<Leak groups={keywords} settings={settings}/>} {page==='hero'&&<ListPage title="효자 키워드" hint={`실제 ROAS가 목표 ${settings.targetRoa}% 이상인 키워드`} groups={keywords.filter(k=>k.orders>0&&k.actualRoa>=settings.targetRoa)} first="효자 키워드"/>}
 {page==='product'&&<ProductDiagnosis comparisons={comparisons} settings={settings} master={master}/>} {page==='placement'&&<Placement rows={rows} settings={settings}/>}
 {page==='rows'&&<Rows rows={rows.filter(r=>[r.keyword,r.product,r.placement].some(v=>v.toLowerCase().includes(query.toLowerCase())))} query={query} setQuery={setQuery} settings={settings}/>}
 {page==='master'&&<Master comparisons={comparisons} master={master} setMaster={setMaster} settings={settings}/>} {page==='sourcing'&&<SourcingCalculator/>} {page==='settings'&&<Settings value={settings} setValue={setSettings} weeks={weeks} deleteWeek={id=>setWeeks(weeks.filter(w=>w.id!==id))}/>} </main>{notice&&<div className="toast">✓ {notice}</div>}
 {uploadOpen&&<Upload close={()=>setUploadOpen(false)} fileRef={fileRef} importWorkbook={importWorkbook} raw={raw} setRaw={setRaw} parseRaw={parseRaw} sample={()=>{setRows(sampleRows);setUploadOpen(false);flash('샘플 데이터를 불러왔습니다.')}}/>}</div>
}

function Dashboard({m,pm,products,comparisons,rows,settings,master,previous,weeks,previousId,setPreviousId,setPage}){const actions=comparisons.map(c=>actionStatus(c.now,master[c.productId]?.requiredRoa,settings)), leak=actions.filter(a=>a.level==='danger').length, scale=actions.filter(a=>a.label==='확대 검토').length;const nonSearch=rows.filter(r=>placementCategory(r.placement)!=='검색').reduce((a,r)=>a+r.cost,0),share=m.cost?nonSearch/m.cost*100:0;const costDelta=compareValue(m.actualCost,pm.actualCost),cpaDelta=compareValue(m.cpa,pm.cpa);return <>
 <section className="weekly-hero"><div className="hero-head"><div><span className="eyebrow">이번 주 광고 한눈에 보기</span><h2>{weekRange(rows)}</h2></div><div className="compare-picker"><label>비교 주차</label><select value={previousId} onChange={e=>setPreviousId(e.target.value)}><option value="">자동 선택</option>{weeks.map(w=><option value={w.id} key={w.id}>{w.label}</option>)}</select></div></div><div className="summary-grid"><div><small>총 실제 광고비</small><b>{won(m.actualCost)}</b></div><div><small>광고주문</small><b>{number(m.orders)}건</b></div><div><small>실제 ROAS</small><b>{pct(m.actualRoa)}</b></div><div><small>CPA</small><b>{won(m.cpa)}</b></div><div><small>누수 주의 상품</small><b>{leak}개</b></div><div><small>확대 검토 상품</small><b>{scale}개</b></div><div><small>비검색 광고비</small><b>{pct(share)}</b></div></div><div className="auto-summary"><b>✦ 주간 자동 요약</b><p>{previous?`이번 주 실제 광고비는 지난주 대비 ${costDelta.rate===null?'신규':`${Math.abs(costDelta.rate).toFixed(1)}% ${costDelta.direction==='up'?'증가':'감소'}`}했고, CPA는 ${cpaDelta.rate===null?'비교 데이터가 없습니다':`${Math.abs(cpaDelta.rate).toFixed(1)}% ${cpaDelta.direction==='down'?'개선':'증가'}했습니다`}. ${scale?`${scale}개 상품은 성과가 좋아 확대 검토 대상입니다.`:''} ${leak?`${leak}개 상품은 누수 또는 수익성 점검이 필요합니다.`:''}`:'지난주 데이터를 저장하거나 비교 주차를 선택하면 변화 요약을 보여드립니다.'}</p></div></section>
 <div className="section-title"><div><h2>이번 주 핵심 성과</h2><p>CPA와 실제 ROAS는 VAT 포함 광고비 기준입니다.</p></div>{previous&&<span>vs {previous.label}</span>}</div><section className="weekly-kpis"><Kpi label="광고비" value={won(m.cost)} now={m.cost} before={pm.cost}/><Kpi label="실제 광고비 (VAT 포함)" value={won(m.actualCost)} now={m.actualCost} before={pm.actualCost}/><Kpi label="광고매출" value={won(m.sales)} now={m.sales} before={pm.sales}/><Kpi label="광고주문" value={`${number(m.orders)}건`} now={m.orders} before={pm.orders} format={number}/><Kpi label="ROAS" value={pct(m.roa)} now={m.roa} before={pm.roa} format={pct}/><Kpi label="실제 ROAS" value={pct(m.actualRoa)} now={m.actualRoa} before={pm.actualRoa} format={pct}/><Kpi label="CPA" value={won(m.cpa)} now={m.cpa} before={pm.cpa} inverse/><Kpi label="CTR" value={pct(m.ctr)} now={m.ctr} before={pm.ctr} format={pct}/><Kpi label="클릭수" value={number(m.clicks)} now={m.clicks} before={pm.clicks} format={number}/></section>
 <div className="two-col priority"><section className="panel"><div className="panel-title"><div><h2>먼저 점검할 상품</h2><p>누수와 전환 문제를 우선 확인하세요.</p></div><button onClick={()=>setPage('product')}>전체 보기 →</button></div>{comparisons.filter(c=>['danger','orange'].includes(actionStatus(c.now,master[c.productId]?.requiredRoa,settings).level)).slice(0,4).map(c=><div className="action-row" key={c.productId}><div><b>{c.product}</b><small>{won(c.now.actualCost)} · {c.now.orders}건 · 실제 ROAS {pct(c.now.actualRoa)}</small></div><Badge status={actionStatus(c.now,master[c.productId]?.requiredRoa,settings)}/></div>)}{!leak&&<Empty>현재 우선 점검할 상품이 없습니다.</Empty>}</section><section className="panel"><div className="panel-title"><div><h2>잘 되고 있는 상품</h2><p>유지 또는 확대 후보입니다.</p></div></div>{comparisons.filter(c=>['good','blue'].includes(actionStatus(c.now,master[c.productId]?.requiredRoa,settings).level)).slice(0,4).map(c=><div className="action-row" key={c.productId}><div><b>{c.product}</b><small>{c.now.orders}건 · 실제 ROAS {pct(c.now.actualRoa)}</small></div><Badge status={actionStatus(c.now,master[c.productId]?.requiredRoa,settings)}/></div>)}</section></div></>}
function Weekly({comparisons,master,settings,notes,setNotes,currentLabel,previous}){const setMemo=(id,type,value)=>setNotes({...notes,[id]:{...(notes[id]||{}),[type]:value}});return <section className="panel page-panel"><div className="panel-title"><div><h2>상품별 주간 비교</h2><p>{currentLabel} vs {previous?.label||'비교 주차 없음'} · CPA와 실제 ROAS는 VAT 포함 기준</p></div></div><div className="table-wrap wide"><table><thead><tr><th>상품</th><th>광고비 이번/지난</th><th>주문 이번/지난</th><th>CPA 이번/지난</th><th>실제 ROAS 이번/지난</th><th>다음 주 액션</th><th>주간 액션 메모</th></tr></thead><tbody>{comparisons.map(c=>{const a=actionStatus(c.now,master[c.productId]?.requiredRoa,settings);return <tr key={c.productId}><td><b>{c.product}</b><small className="block">{c.productId}</small></td><ComparePair now={c.now.cost} before={c.before.cost} format={won}/><ComparePair now={c.now.orders} before={c.before.orders} format={number}/><ComparePair now={c.now.cpa} before={c.before.cpa} format={won} inverse/><ComparePair now={c.now.actualRoa} before={c.before.actualRoa} format={pct}/><td><Badge status={a}/></td><td className="memo-cell"><small>지난주: {notes[c.productId]?.previous||'—'}</small><textarea value={notes[c.productId]?.current||''} onChange={e=>setMemo(c.productId,'current',e.target.value)} placeholder="다음 주 조치 입력"/><button onClick={()=>setNotes({...notes,[c.productId]:{previous:notes[c.productId]?.current||'',current:''}})}>다음 주로 넘기기</button></td></tr>})}</tbody></table></div></section>}
function ComparePair({now,before,format,inverse}){return <td><b>{format(now)}</b><small className="block">지난 {format(before)}</small><Delta now={now} before={before} format={format} inverse={inverse}/></td>}
function Leak({groups,settings}){const leaks=groups.filter(g=>leakLevel(g,settings).rank>0).sort((a,b)=>b.cost-a.cost);return <section className="panel page-panel"><div className="panel-title"><div><h2>누수 키워드 3단계 진단</h2><p>주문이 없는 키워드를 클릭·광고비 기준으로 관찰 / 의심 / 높음으로 나눕니다.</p></div></div><div className="table-wrap"><table><thead><tr><th>키워드</th><th>단계</th><th>클릭</th><th>광고비</th><th>실제 광고비</th><th>권장 확인</th></tr></thead><tbody>{leaks.map(g=>{const l=leakLevel(g,settings);return <tr key={g.name}><td><b>{g.name}</b></td><td><Badge status={l}/></td><td>{g.clicks}</td><td>{won(g.cost)}</td><td>{won(g.actualCost)}</td><td>{l.rank===1?'데이터 추가 수집':l.rank===2?'검색어·상품 경쟁력 점검':'입찰 축소 또는 전환 요소 우선 점검'}</td></tr>})}</tbody></table></div></section>}
function ProductDiagnosis({comparisons,settings,master}){return <section className="panel page-panel"><div className="panel-title"><div><h2>상품 퍼널 및 액션 진단</h2><p>자동 진단은 운영 결정을 돕는 참고용이며 실제 상품 상황과 함께 판단하세요.</p></div></div><div className="diagnosis-grid">{comparisons.map(c=>{const f=funnelDiagnosis(c.now,settings),a=actionStatus(c.now,master[c.productId]?.requiredRoa,settings);return <article key={c.productId}><div><small>{c.productId}</small><h3>{c.product}</h3></div><Badge status={a}/><div className="funnel"><span>노출 <b>{number(c.now.impressions)}</b></span><i>→</i><span>클릭 <b>{number(c.now.clicks)}</b></span><i>→</i><span>주문 <b>{number(c.now.orders)}</b></span></div><h4>{f.label}</h4><p>{f.hint}</p></article>})}</div></section>}
function Placement({rows,settings}){const cats=['검색','비검색','오디언스 플러스','기타'].map(name=>({name,rows:rows.filter(r=>placementCategory(r.placement)===name)})).map(x=>({name:x.name,...metrics(x.rows,settings)})), total=metrics(rows,settings), non= cats.filter(c=>c.name!=='검색').reduce((a,c)=>a+c.cost,0),share=total.cost?non/total.cost*100:0;return <><div className={`placement-alert ${share>settings.nonSearchWarningRate?'warning':''}`}>{share>settings.nonSearchWarningRate?'⚠':'◎'} 비검색 영역이 전체 광고비의 <b>{pct(share)}</b>를 차지하고 있습니다. <span>비중만으로 성과를 판단하지 말고 주문·CPA·실제 ROAS를 함께 확인하세요.</span></div><section className="panel page-panel"><div className="panel-title"><div><h2>검색 / 비검색 지면 분석</h2><p>비검색 경고 기준 {settings.nonSearchWarningRate}%</p></div></div><div className="table-wrap"><table><thead><tr><th>영역</th><th>광고비</th><th>실제 광고비</th><th>전체 비중</th><th>주문</th><th>CPA</th><th>실제 ROAS</th></tr></thead><tbody>{cats.map(c=><tr key={c.name}><td><b>{c.name}</b></td><td>{won(c.cost)}</td><td>{won(c.actualCost)}</td><td>{pct(total.cost?c.cost/total.cost*100:0)}</td><td>{c.orders}</td><td>{won(c.cpa)}</td><td>{pct(c.actualRoa)}</td></tr>)}</tbody></table></div></section></>}
function ListPage({title,hint,groups,first}){return <section className="panel page-panel"><div className="panel-title"><div><h2>{title}</h2><p>{hint}</p></div><span className="count">총 {groups.length}개</span></div>{groups.length?<Table groups={groups} first={first}/>:<Empty>조건을 충족한 데이터가 없습니다.</Empty>}</section>}
function Rows({rows,query,setQuery,settings}){return <section className="panel page-panel"><div className="panel-title"><div><h2>행별 진단</h2><p>원본 데이터의 VAT 포함 성과와 진단을 확인합니다.</p></div><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕ 상품, 키워드 검색"/></div><div className="table-wrap"><table><thead><tr><th>날짜 / 상품</th><th>키워드</th><th>실제 광고비</th><th>주문</th><th>실제 ROAS</th><th>진단</th></tr></thead><tbody>{rows.map(r=>{const d=classify(r,settings),mm=metrics([r],settings);return <tr key={r.id}><td><b>{r.product}</b><small className="block">{r.productId} · {r.date}</small></td><td>{r.keyword}</td><td>{won(mm.actualCost)}</td><td>{r.orders}</td><td>{pct(mm.actualRoa)}</td><td><Badge status={d}/></td></tr>})}</tbody></table></div></section>}
function Master({comparisons,master,setMaster,settings}){const update=(id,key,value)=>setMaster({...master,[id]:{...(master[id]||{}),[key]:Number(value)}});return <section className="panel page-panel"><div className="panel-title"><div><h2>상품 마스터 · 필요 ROAS</h2><p>상품별 손익 기준을 입력하면 실제 ROAS와 비교해 상태를 표시합니다.</p></div></div><div className="table-wrap"><table><thead><tr><th>상품ID</th><th>상품명</th><th>필요 ROAS</th><th>실제 ROAS</th><th>수익성 상태</th><th>광고매출</th></tr></thead><tbody>{comparisons.map(c=>{const required=master[c.productId]?.requiredRoa||settings.targetRoa,s=profitabilityStatus(c.now.actualRoa,required,settings);return <tr key={c.productId}><td><b>{c.productId}</b></td><td>{c.product}</td><td><div className="inline-input"><input type="number" value={required} onChange={e=>update(c.productId,'requiredRoa',e.target.value)}/><span>%</span></div></td><td>{pct(c.now.actualRoa)}</td><td><Badge status={s}/></td><td>{won(c.now.sales)}</td></tr>})}</tbody></table></div></section>}
function Settings({value,setValue,weeks,deleteWeek}){const fields=[['marginRate','평균 마진율','예상 순이익 계산','%'],['shippingCost','건당 배송비','주문당 평균 배송비','원'],['targetRoa','기본 필요 ROAS','상품별 값이 없을 때 적용','%'],['roaComfortRate','ROAS 여유 구간','필요 ROAS 대비 여유·경계 범위','%'],['nonSearchWarningRate','비검색 광고비 경고 기준','전체 광고비 중 비검색 비중','%'],['leakSuspectClicks','누수 의심 클릭수','주문 0건 기준','회'],['leakHighClicks','누수 높음 클릭수','주문 0건 기준','회'],['leakSuspectCost','누수 의심 광고비','주문 0건 기준','원'],['leakHighCost','누수 높음 광고비','주문 0건 기준','원'],['minImpressions','최소 노출 기준','노출 부족 진단 기준','회'],['minClicks','최소 클릭 기준','데이터 부족 액션 기준','회'],['healthyCtr','정상 CTR 기준','클릭 부족 진단 기준','%'],['conversionClicks','전환 판단 클릭수','클릭 충분·전환 없음 기준','회']];return <><section className="panel settings"><div className="panel-title"><div><h2>사용자 진단 기준</h2><p>고정 판단이 아닌 내 광고 운영 기준으로 조정하세요. 변경사항은 자동 저장됩니다.</p></div></div>{fields.map(([key,label,hint,unit])=><label key={key}><span><b>{label}</b><small>{hint}</small></span><div><input type="number" value={value[key]} onChange={e=>setValue({...value,[key]:Number(e.target.value)})}/><em>{unit}</em></div></label>)}</section><section className="panel week-list"><div className="panel-title"><div><h2>저장된 주간 데이터</h2><p>비교에 필요 없는 과거 주차를 삭제할 수 있습니다.</p></div></div>{weeks.map(w=><div key={w.id}><span><b>{w.label}</b><small>{w.rows.length}행 · {new Date(w.savedAt).toLocaleString('ko-KR')}</small></span><button onClick={()=>confirm('이 주차 데이터를 삭제할까요?')&&deleteWeek(w.id)}>삭제</button></div>)}{!weeks.length&&<Empty>저장된 주차가 없습니다.</Empty>}</section></>}
function Upload({close,fileRef,importWorkbook,raw,setRaw,parseRaw,sample}){return <div className="modal-back" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="modal"><button className="close" onClick={close}>×</button><div className="modal-icon">↑</div><h2>이번 주 광고 데이터 불러오기</h2><p>XLSX, XLS, CSV 파일 또는 쿠팡 보고서 RAW를 사용하세요.</p><div className="drop" onClick={()=>fileRef.current.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();importWorkbook(e.dataTransfer.files[0])}}><b>파일을 끌어다 놓거나 클릭하세요</b><small>.xlsx · .xls · .csv (최대 20MB)</small><input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>importWorkbook(e.target.files[0])}/></div><div className="or"><span/>또는 RAW 붙여넣기<span/></div><textarea value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'날짜\t상품ID\t상품명\t키워드\t노출수\t클릭수\t광고비\t주문수\t매출액'}/><button className="primary full" disabled={!raw.trim()} onClick={parseRaw}>붙여넣은 데이터 분석</button><button className="sample" onClick={sample}>샘플 데이터로 둘러보기 →</button></section></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
